# GitHub Pages / Jekyll configuration
title: Seriously
description: Your AI-Powered Personal Nutrition Coach

# Markdown processing
markdown: kramdown

# Include markdown files
include:
  - privacy.md
  - terms.md

# Plugins
plugins:
  - jekyll-relative-links

# Enable relative links
relative_links:
  enabled: true
  collections: true